name: fitness_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  percent_indicator: ^4.2.4
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sportive_woman.png
    - assets/images/logo.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/google.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/profile.png
    - assets/images/fullbody.png
    - assets/images/cardio.png
    - assets/images/strength.png
    - assets/images/hiit.png
    - assets/images/fullbodyw.png
    - assets/images/backw.png
    - assets/images/shoulderw.png
    - assets/images/upperbodyw.png
    - assets/images/shoulderw.png
    - assets/images/lowerbodyw.png
    - assets/images/corew.png
    - assets/images/cardiow.png
    - assets/images/armw.png

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Bold.ttf
        - asset: fonts/Oswald-Medium.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 700
