name: fitness_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  percent_indicator: ^4.2.4
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  fl_chart: ^0.69.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  share_plus: ^10.1.3
  in_app_review: ^2.0.10
  path: ^1.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appicon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/sportive_woman.png
    - assets/images/logo.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/google.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/profile.png
    - assets/images/fullbody.png
    - assets/images/cardio.png
    - assets/images/strength.png
    - assets/images/hiit.png
    - assets/images/fullbodyw.png
    - assets/images/backw.png
    - assets/images/shoulderw.png
    - assets/images/upperbodyw.png
    - assets/images/shoulderw.png
    - assets/images/lowerbodyw.png
    - assets/images/corew.png
    - assets/images/cardiow.png
    - assets/images/armw.png
    - assets/images/burpees.png
    - assets/images/jumping_jacks.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Regular.ttf
        - asset: fonts/Inter_18pt-Bold.ttf
          weight: 600
        - asset: fonts/Inter_18pt-Medium.ttf
          weight: 500
